version: '3'
services:
  mysql:
    image: 'mysql:latest'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=exercise
      - MYSQL_USER=tomer
      - MYSQL_PASSWORD=123456
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    environment:
      - MYSQL_DB=exercise
      - MYSQL_USER=tomer
      - MYSQL_PASSWORD=123456
      - MYSQL_HOST=mysql
    depends_on:
      - mysql
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
    environment:
      - WDS_SOCKET_PORT=0