version: '3'
services:
  mysql:
    image: 'mysql:latest'
    restart: always
    env_file: ./compose.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    env_file: ./compose.env
    depends_on:
      mysql:
        condition: service_healthy
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
    environment:
      - WDS_SOCKET_PORT=0