- name: Second playbook
  hosts: jenkinsserver
  become: true
  gather_facts: no
  tasks:
    - name: Ensure Jenkins repository is added
      ansible.builtin.yum_repository:
        name: jenkins-ci
        description: jenkins-ci package repository
        baseurl: http://pkg.jenkins.io/redhat
        gpgkey: https://pkg.jenkins.io/redhat/jenkins.io.key
        gpgcheck: yes
    - name: Ensure gpp key is imported
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io.key
    - name: Ensure Jenkins and java-devel package installed
      ansible.builtin.yum:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - jenkins
          - java-devel
    - name: Ensure systemd daemon reloaded
      command: systemctl daemon-reload
    - name: Ensure Jenkins service is enabled and started
      ansible.builtin.service:
        name: jenkins
        state: started
